# -*- coding: utf-8 -*-
"""data_cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SQt_fVXVx3mW5ILWOaOmZeg7TD2jguan
"""

def clean_data(df):

    """Performs ETL: fixes swapped columns, elevation errors, and typos."""

    # 1. Swap the mislabeled columns
    df = df.rename(columns={'Crop_type': 'Annual_yield', 'Annual_yield': 'Crop_type'})

    # 2. Fix negative elevation values
    df['Elevation'] = df['Elevation'].abs()

    # 3. Standardize crop names
    df['Crop_type'] = df['Crop_type'].str.strip().replace({
        'cassaval': 'cassava',
        'wheatn': 'wheat',
        'teaa': 'tea'
    })

    return df