# -*- coding: utf-8 -*-
"""data_ingestion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dUFk3SYioNT9vrvY3TQ8LfsFgMut4JxF
"""

import pandas as pd
from sqlalchemy import create_engine, text

def ingest_data(db_path):

    """Connects to SQLite and joins the 4 agricultural tables."""

    engine = create_engine(f'sqlite:///{db_path}')
    query = """
    SELECT * FROM geographic_features
    JOIN weather_features ON geographic_features.Field_ID = weather_features.Field_ID
    JOIN soil_and_crop_features ON geographic_features.Field_ID = soil_and_crop_features.Field_ID
    JOIN farm_management_features ON geographic_features.Field_ID = farm_management_features.Field_ID
    """
    with engine.connect() as conn:
        df = pd.read_sql_query(text(query), conn)

    # Drop duplicate Field_ID columns from the join

    df = df.drop(columns='Field_ID')
    return df