# -*- coding: utf-8 -*-
"""analysis_tools.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wcY3iiYUTRy7ZTO24XbKPaQSOAKuqVC3
"""

def analyse_soil_fertility(df):
    return df.groupby('Soil_type')['Soil_fertility'].mean()

def climate_geography_influence(df, column):
    cols = ['Elevation', 'Min_temperature_C', 'Max_temperature_C', 'Rainfall']
    return df.groupby(column)[cols].mean()

def find_good_conditions(df, crop_type):
    avg_yield = df['Standard_yield'].mean()
    conditions = (
        (df['Crop_type'] == crop_type) &
        (df['Standard_yield'] > avg_yield) &
        (df['Ave_temps'] >= 12) & (df['Ave_temps'] <= 15) &
        (df['Pollution_level'] < 0.0001)
    )
    return df[conditions]