# -*- coding: utf-8 -*-
"""visualizations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bvLZS7fWOF_auHhxngnorSK-0ITgvhMm
"""

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

def generate_visuals(df):
    """Generates and saves key agricultural insights."""

    # Set a professional style
    sns.set_theme(style="whitegrid")

    # 1. Soil Fertility by Soil Type (Bar Chart)
    plt.figure(figsize=(10, 6))
    fertility_data = df.groupby('Soil_type')['Soil_fertility'].mean().sort_values()
    fertility_data.plot(kind='barh', color='teal')
    plt.title('Average Soil Fertility by Soil Type')
    plt.xlabel('Fertility Score')
    plt.ylabel('Soil Type')
    plt.tight_layout()
    plt.savefig('visuals/soil_fertility.png')
    plt.close()

    # 2. Yield vs. Pollution (Scatter Plot)
    plt.figure(figsize=(10, 6))
    sns.scatterplot(data=df, x='Pollution_level', y='Standard_yield', hue='Crop_type', alpha=0.6)
    plt.title('Impact of Pollution on Crop Yield')
    plt.savefig('visuals/pollution_impact.png')
    plt.close()

    # 3. Rainfall Distribution for Top Crops (Box Plot)
    plt.figure(figsize=(10, 6))
    sns.boxplot(data=df, x='Crop_type', y='Rainfall')
    plt.xticks(rotation=45)
    plt.title('Rainfall Distribution per Crop Type')
    plt.savefig('visuals/rainfall_distribution.png')
    plt.close()

    print("Visualizations saved to the 'visuals/' folder.")