# -*- coding: utf-8 -*-
"""the_orchestrator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11GaLvaOP1YgpCMvnYoe7IdWN6kpMJEz0
"""

from scripts.data_ingestion import ingest_data
from scripts.data_cleaning import clean_data
from scripts.analysis_tools import find_good_conditions

# 1. Ingest
raw_df = ingest_data('Maji_Ndogo_farm_survey_small.db')

# 2. Clean
cleaned_df = clean_data(raw_df)

# 3. Analyze
top_fields = find_good_conditions(cleaned_df, 'tea')

print(f"Analysis Complete. Found {len(top_fields)} high-potential fields.")
print(top_fields.head())